### PR TITLE
Bam tag histogram mrfifo

### PR DESCRIPTION
**Pull request by marvin-jens**
# Replacing dropseq-tools BamTagHistogram 

This tool has become a pain-point as we now routinely have hundreds of millions of legitimate, spatial barcodes in open-st data. 
This PR features a complete, drop-in replacement re-written in python using `mrfifo`. It is about 10x faster and uses less RAM. I've included unit test code and also run it on some real-world data, observing identical output compared to dropseq-tools.

Unless you run into issues, I'd like to merge this into fast-cmdline (and possibly master) asap.

Best,
  -Marvin

### CODE REVIEW

**Comment by danilexn** [comment]
Thanks so much for the amazing code, Marvin! I started testing on the tiny spatial data and Open-ST mouse hippocampus, and ran into some minor issues:

- Several dependencies missing from the environment.yaml, I will push some commits fixing this
- A file `BamTagHistogram.log` is created at the root of the `spacemake` project (because of the `make_minimal_parser`). Should this be created at the specific project/sample folders?
- I've been running into issues with the `rerun_triggers` flag -- not all snakemake versions seem to support it (e.g., the newest we support in our environment.yaml).

As soon as the tests finish on the Open-ST data, I will report back and we can merge this into fast-cmdline and master. Also, I will run on very large Open-ST data (>10B reads) to explore the limits of the pipeline in terms of mem usage.

**Comment by danilexn** [comment]
It worked with the tiny data, but then the `out_readcounts_prealigned.txt.gz` file and others are empty with larger (real) datasets. Will investigate...

**Comment by danilexn** [comment]
Tested, works as advertised :)

Maybe @nukappa can run another sample, but LGTM as soon as we address the minor points above (making sure installation works fine, and the `.log` file). Also, we should consider putting `--min-count 1` in both calls to `BamTagHistogram` at `main.smk`, otherwise it might not work well with Open-ST data

**Comment by nukappa** [comment]
Running tests and will report soon
- [ ] Tests passed!

**Comment by danilexn** [comment]
> Thanks so much for the amazing code, Marvin! I started testing on the tiny spatial data and Open-ST mouse hippocampus, and ran into some minor issues:
> 
>     * Several dependencies missing from the environment.yaml, I will push some commits fixing this
> 
@marvin-jens will address in `mrfifo`

>     * A file `BamTagHistogram.log` is created at the root of the `spacemake` project (because of the `make_minimal_parser`). Should this be created at the specific project/sample folders?
> 
This was fixed
>     * I've been running into issues with the `rerun_triggers` flag -- not all snakemake versions seem to support it (e.g., the newest we support in our environment.yaml).
> 
Ready to merge
> 
> As soon as the tests finish on the Open-ST data, I will report back and we can merge this into fast-cmdline and master. Also, I will run on very large Open-ST data (>10B reads) to explore the limits of the pipeline in terms of mem usage.

**Ready to test by @nukappa and merge into `fast-cmdline`**

**Comment by marvin-jens** [comment]
Everything here got merged into fix-newmaster a while ago. So this PR is redundant with fix-newmaster, which was just merged into master.

**Pull request closed without merging**
