### PR TITLE
Bowtie2 support

### PR DESCRIPTION
**Pull request by marvin-jens**
Dear Tamas & Nikos,

as discussed on previous occasions, I have built a map_strategy feature, allowing to define - for each sample - how spacemake is supposed to map the reads. The map_strategy can extract unmapped reads from one alignment and re-align these to another index, *or* it can align the same reads in parallel to multiple indices. These features can also be combined. The result of a mapping will be named automatically to make dependencies and rules match. For convenience and integration with existing code, each mapped BAM can be symlinked to a desired name (e.g. "final.polyA_adapter_trimmed.bam"). An example:

  `bowtie2:rRNA->STAR:genome:final`

This would instruct to first map all reads with bowtie2 against ribosomal RNA and then the *unmapped* reads to the genome using STAR. The BAM files would be named `rRNA.bowtie2.bam` and `genome.STAR.bam`. A symlink `final.polyA_adapter_trimmed.bam` would be created to the latter.
If annotation is defined for a reference, then alignments are automatically annotation tagged (if you like, for rRNA as well).
(In the future, we can use these mechanisms to map against CITE-seq sequences, or other multi-omics, sequence-counting methods, and count into a DGE right away).

Most of the code lives in `mapping.smk`  (the STAR alignment rule in dropseq.smk is now commented out. dropseq.smk now largely holds pre-processing, which can be improved further -- but that will be another pull-request).

There are some important **incompatible changes** that need discussion and the addition of a migration path: A species can now have multiple 'references'. Each reference can have it's own annotation, sequence (used to be 'genome'), and optional bt2_flags, STAR_flags, bt2_index and index_dir (kept the name for compatibility, but should be STAR_index).

Here's the relevant section from my config.yaml:

    species:
      human:
        genome:
          annotation: /data/rajewsky/annotation/GRCh38/gencode.v36.annotation.gtf
          sequence: /data/rajewsky/genomes/GRCh38.p13/GRCh38.p13.fa
          index_dir: "species_data/human/star_index"
    
        mirgenedb:
          annotation: /data/rajewsky/projects/sc_smRNA_marvin/mirgenedb/fake_annotation.gtf
          sequence: /data/rajewsky/projects/sc_smRNA_marvin/mirgenedb/hsa-mature.fa
          # more sensitive score cutoffs for miRNA mapping. score 30=15nt perfect match
          bt2_flags: "--score-min=C,30 -L 10 -D 50 -R 50 --local --ignore-quals"
          bt2_index: /data/rajewsky/projects/sc_smRNA_marvin/mirgenedb/hsa-mature.fa
    
        rRNA:
          # annotation: lookup:/data/rajewsky/projects/sc_smRNA_marvin/aRNA_lkup.tsv
          sequence: /data/rajewsky/projects/sc_smRNA_marvin/rRNA/rRNA_hsa.fa
          # need 75% of best-possible score to match here
          bt2_flags: "--score-min=L,0,1.5 -L 10 -D 50 -R 50 --local --ignore-quals"
          bt2_index: /data/rajewsky/projects/sc_smRNA_marvin/rRNA/rRNA_hsa
    
      mouse:
        genome:
          annotation: /data/rajewsky/annotation/mm39/gencode.vM27.primary_assembly.annotation.gtf
          sequence: /data/rajewsky/genomes/mm39/GRCm39.primary_assembly.genome.fa

I have changed the semantics of the commandline tool accordingly (now you do not add a species, you add a reference and the reference belongs to a species name), and also added the required plumbing to project_df and some helper functions to get genome sequences, annotation and indices (these accept a ref="genome" kwarg now to select other references). What is broken right now is the use of rRNA counts in QC reports, and the rules to *build* a mapping index.
I would appreciate your feedback on these changes and once we agree on everything would be happy to add these back in as well as some migration code to detect the previous species definitions and move them to the new format.

Best regards,
  -Marvin

### CODE REVIEW

**Comment by sztankatt** [comment]
> 

Hi @marvin-jens,

Thanks, this looks super! I think its very useful to have this feature implemented, as it further boosts the flexibility offered by spacemake. Right now I am fully occupied with my thesis, so didn't yet have a chance to look at the code more closely, I will try to do this over the weekend.

A few comments/questions regardig the design:

- I see that what changes in the config.yaml, is that each species will be able to have several annotation+sequence pairs. For this you renamed the 'genome' to 'sequence'. And what 'genome' now means is basically the chromosomal DNA sequences.  Is this correct?
- I would keep the `spacemake config add_species` command, and add the other command (like `spacemake config add_reference`) which is more complicated and can has more options. I think still the majority of spacemake use-cases will deal with mapping with STAR using a single sequences+annotation pair. The only thing that needs to be changing for the `add_species` command is to replace `--genome` with `--reference`, so that it follows the new naming.
- Kind of as a followup from the previous: does the user need to define a mapping strategy for each sample during configuration? If a species is added with the `add_species` command for instance, I would just create the right entry in the config.yaml, and then define the mapping strategy to only contain mapping with STAR (and also with bowtie2, if the `--rRNA_genome` flag was provided. The mapping strategy could also be deduced somehow from the config, if a species only has one 'genome' entry. I just really think that we should keep things as simple as possible for someone who only wants to map once.

Best,
Tamas

**Comment by marvin-jens** [comment]
Hi Tamas, I've had some issues logging into my github from home but all set now. Hence the delayed response. Regarding your questions:
1) Correct. You can add multiple references to a species and if you name it 'genome' that should probably mean chromosomes et al. (as we had before)
2) Currently, I've modified the add_species command almost exactly along what you proposed. It in fact adds a reference (and only indirectly the species, if needed) and the reference name (`--name`) defaults to 'genome'. As you pointed out `--genome` is renamed to `--sequence` You can now run add_species repeatedly, as long as the reference-name differs. Not all features (such as bt2_flags, STAR_flags,...) are exposed yet though. I can add that before merge of course.
3) No. I follow your recipe for migration of project_df (longreads, ...) to add a default value in case no mapping strategy is provided. The default is `STAR:genome:final` . I guess we need to also migrate the species config to the new format (no migration implemented yet) and if we have rRNA, we can change the map_strategy missing values to `bowtie2:rRNA,STAR:genome:final` which would map all reads to rRNA and genome in parallel (I believe that's what we currently do by default). User could change that to `bowtie2:rRNA->STAR:genome:final` which would actually implement "in silico rRNA depletion" in the sense that rRNA-mapping reads would not even be considered for genome alignments.

**Comment by marvin-jens** [comment]
Hi Tamas, as discussed in slack i've added support for custom snakemake code and a general mechanism by which such snakemake modules can register output files as dependency of the master rule (top-level). This is to ensure that these files will be created by `spacemake run` via the appropriate rules.

**Comment by marvin-jens** [comment]
I've just tested the whole shebang from scratch (spacemake init), adding rRNA, miRNA and genome sequences (just chr22 for testing) with a hand-crafted set of test-reads and it all appears to work. One thing I need guidance with is the selection of multi-mapped reads. I believe this was implemented by piping through a custom script after STAR and it's probably not yet put back into place.

**Comment by marvin-jens** [comment]
Quick update: 

-  spacemake/unittests.py runs a small test-suite and is already quite helpful.
-  cmdline interface for `add_species` now also exposes `--BT2_flags` and `--STAR_flags` (although this is considered _expert_ level fiddling).
-  migration path from old config.yaml species/genome+annotation+rRNA_genome to current species/[genome|rRNA]/sequence+annotation

**Comment by marvin-jens** [comment]
Oh, and also: the multi-mapping logic should work exactly as before (since it only requires get_final_bam as input and that hasn't changed). But this needs a test-case. Working on more test-data with Nikos...

**Pull request merged**
