### PR TITLE
automatic stitching and puck filtering

### PR DESCRIPTION
**Pull request by danilexn**
This PR addresses two new functionalities:

- **Stitching of spatial pucks**. Via a new puck variable, `coordinate_system`, data corresponding to several spatial pucks can be automatically "stitched" together into a single h5ad file, with global coordinates. This constitutes a `puck_collection` – this naming is used in the generated files. Thus, after creating the individual h5ad files, the pipeline will call `spacemake.spatial.puck_collection` to generate a single h5ad file from all available. The `coordinate_system`(s) are expressed via a csv file, with columns `puck_id,x_offset,y_offset,z_offset`. These offsets are summed to the `obsm["spatial"]` variable of each individual h5ad, following the corresponding `puck_id`. Then, the single `*.puck_collection.h5ad` file is generated for each project and sample. This is automatically part of the main pipeline, if the puck variable `coordinate_system` points to a valid csv offset coordinate file. This can be run separately from the main pipeline via the script `spacemake.spatial.puck_collection`. Example global coordinate systems can be generated with the script in `spacemake.data.puck_collection.create_novaseq_S4_coordinate_system`
- **Automatic exclusion of puck barcode files with not _enough_ matches to barcodes from the sample**. Via a new `run_mode` variable, `spatial_barcode_min_matches`, only puck barcode files with at least a `spatial_barcode_min_matches` proportion of matching barcodes (respect to the sample) will receive a _pass_ to continue along rest of the pipeline. For efficiency, barcode matches are computed twice. First, barcodes are extracted from unaligned reads, and matched again the indicated pucks – this occurs in parallel to preprocessing of reads and alignment. Second, barcode matches are computed after alignment. Two intermediate files are generated, `puck_count_prealigned_barcode_matches.csv` and `puck_count_barcode_matches.csv`, with columns `puck_barcode_file_id,puck_barcode_file,parsed_barcode_file,n_barcodes,n_matching,matching_ratio,pass_threshold`. The last column, `pass_threshold`, will be used by spacemake before continuing the pipeline in order to determine whether a `puck_barcode_file` should be further considered. Leaving `spatial_barcode_min_matches=0` is equivalent to the pipeline in `spacemake<=0.7.1`. This can also be run separately from the main pipeline via the script `spacemake.snakemake.scripts.n_intersect_sequences`.

Several features remain to be implemented / Some issues need to be addressed:

- [x] QC and reports do not run for the automatically generated `puck_collection`
- [x] choose the `default` value (empty) for the `coordinate_system` puck variable when not specified
- [x] Complete stitching script to keep `uns[*]` variables
- [x] Modify rule `puck_collection_stitching` in `main.smk` to create a `spatial_barcodes_puck_collection.csv` file, to ensure full compatibility with qc sheets – otherwise, the QC sheet does not contain the spatial plots.
- [x] Complete code and example documentation (e.g., more detailed explanation of coordinate systems, generating custom global coordinate systems)

From @nukappa ([see comment below](https://github.com/rajewsky-lab/spacemake/pull/61#issuecomment-1432554025))
- [x]  Seems like QC and automated report for collection does not have spatial plots? (https://github.com/rajewsky-lab/spacemake/pull/61/commits/de5564b88ecc82bee32f35559dc992fb01d10d39)
- [x] Make sure there's a sensible default for single-cell projects (I think it currently throws error and stops if no pucks are provided) (https://github.com/rajewsky-lab/spacemake/pull/61/commits/39691202cf258aa0a29ce627b6836fd51d43eb2b)
- [x] Computing matches at some point seems to write on the project_df.csv (and reduces the # of tile files). Can that be a problem due to parallel processing of different samples?

### CODE REVIEW

**Comment by danilexn** [comment]
@reviewers don't worry,
out of the 5,579 new lines, 4,369 are a csv file

**Comment by danilexn** [comment]
The commit #[037a1ed](https://github.com/rajewsky-lab/spacemake/pull/61/commits/037a1ed3250d85fe7668443f3c7f500c7db9ea0c) addresses #50

**Comment by nukappa** [comment]
Also:
- [ ] Make sure there's a sensible default for single-cell projects (I think it currently throws error and stops if no pucks are provided)

**Comment by danilexn** [comment]
Thanks for your comments, @nukappa!

>     * [ ]  Seems like QC and automated report for `collection` does not have spatial plots?
Yes, I fixed that already with some commits that I forgot to push.

>     * [ ]  Make sure there's a sensible default for single-cell projects (I think it currently throws error and stops if no pucks are provided)
Right, I will test with non-spatial single-cell projects - thanks!

>     * [ ]  Computing matches at some point seems to write on the `project_df.csv` (and reduces the # of tile files). Can that be a problem due to parallel processing of different samples?
In principle, the `project_df.csv` is overwritten via 
https://github.com/rajewsky-lab/spacemake/blob/72425d55f8d1d3cef2247229d70064b520ca4675/spacemake/smk.py#L564-L565
and
https://github.com/rajewsky-lab/spacemake/blob/72425d55f8d1d3cef2247229d70064b520ca4675/spacemake/smk.py#L585-L586

so, this happens only once for the whole spacemake run command - globally for all project/samples. I don't think this would be an issue regarding parallel processing. Actually, spacemake already overwrites the `project_df.csv` at the end of the pipeline run, in the same fashion, e.g.,

https://github.com/rajewsky-lab/spacemake/blob/72425d55f8d1d3cef2247229d70064b520ca4675/spacemake/smk.py#L607

**Comment by nukappa** [comment]
Thank you @danilexn for the detailed answer, I confirm that all boxes are ticked :)

**Comment by danilexn** [comment]
I have added the documentation to the functions. 

This is now ready for the final tests.

**Pull request merged**
